"""extend_document_metadata

Revision ID: 30e5ba501d7a
Revises: 986d5df9843a
Create Date: 2026-07-03 03:38:05.056765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e5ba501d7a'
down_revision: Union[str, Sequence[str], None] = '986d5df9843a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('parse_status', sa.String(length=20), nullable=False, server_default="pending"))
    op.add_column('documents', sa.Column('embedding_status', sa.String(length=20), nullable=False, server_default="pending"))
    op.add_column('documents', sa.Column('chunk_count', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('documents', sa.Column('error_message', sa.String(length=1000), nullable=True))
    op.add_column('documents', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('processing_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_completed_at')
    op.drop_column('documents', 'processing_started_at')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'embedding_status')
    op.drop_column('documents', 'parse_status')
    # ### end Alembic commands ###
