"""add_vectorstore_status

Revision ID: 7abffc416842
Revises: 30e5ba501d7a
Create Date: 2026-07-03 13:40:54.350731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7abffc416842'
down_revision: Union[str, Sequence[str], None] = '30e5ba501d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('vectorstore_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('documents', sa.Column('vector_count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column("documents", "vectorstore_status", server_default=None)
    op.alter_column("documents", "vector_count", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'vector_count')
    op.drop_column('documents', 'vectorstore_status')
    # ### end Alembic commands ###
